### ISSUE TITLE
Please provide performance metrics in the benchmarks 

### ISSUE THREAD

**Issue by nickchomey** [pemistahl/lingua-py#122]
I'm impressed by the accuracy of Lingua as compared to even fasttext, but it would be very useful to also see performance metrics in the benchmarks to determine if that accuracy comes at a cost. Likewise it would be useful for comparing lingua's low and high accuracy modes.

**Comment by pemistahl** [comment]
In chapter 9.5 of the README it says: 
_Lingua's high detection accuracy comes at the cost of being noticeably slower than other language detectors._

The statistical models in Lingua are larger than those of similar libraries. So querying them takes more time.

There is a [benchmark script](https://github.com/pemistahl/lingua-py/blob/main/scripts/benchmark.py) in this repo which gives you a clue how performant the library is. You can run it locally with poetry:

```
poetry run python3 scripts/benchmark.py
```

**Comment by datatalking** [comment]
@nickchomey I'm relatively new to this repo but it has more languages than the translation repo I have been using. Could help test and show an "output chart" or help craft then submit a PR for this, so I'm willing to collab with you to look at a few options to generate the stats.

**Comment by pemistahl** [comment]
Performance metrics are now provided in the [README](https://github.com/pemistahl/lingua-py#6-how-fast-is-it).
