### ISSUE TITLE
How can we make the model check the language by itself, without the need to provide a list of languages in advance?

### ISSUE THREAD

**Issue by Alex-Songs** [pemistahl/lingua-py#151]
How can we make the model check the language by itself, without the need to provide a list of languages in advance?

**Comment by Alex-Songs** [comment]
@xD0135 Thanks

**Comment by pemistahl** [comment]
By assuming that your issue is resolved, I close it now. Please read all the documentation before opening issues. Most questions ought to be covered by the docs. Thank you.
