### ISSUE TITLE
get_language_of takes too long

### ISSUE THREAD

**Issue by Vasiliy566** [pemistahl/lingua-py#157]
I im profiling my code and find that [get_language_of](https://github.com/pemistahl/lingua-py/blob/f76c1d3d3fad87e3154d64fa75f03d92ce4463cd/lingua/detector.py#L270) takes too long, maybe in lib it can be flag as example `fast=True` to ignore logic inside with detecting two languages and detect just one and return in? It would be helpful for users that needs fast analyse.

OR

I analyse huge texts, maybe someone have experiance with analyse just peace of text to speed up?

**Comment by pemistahl** [comment]
Hi, I'm working on creating Python bindings for my Rust port of Lingua. As soon as this is done, you probably won't have any performance problems anymore.
