### ISSUE TITLE
English is detected as Sotho too often

### ISSUE THREAD

**Issue by iwtu** [pemistahl/lingua-py#158]
English language is detected so often, then if I use the rule: replace Sotho with English, it will work.

**Comment by pemistahl** [comment]
Do you build the language detector from all available languages? Please give me concrete examples for which my library produces wrong results. Otherwise, your issue is no help for me to improve the algorithm. Thank you.

**Comment by iwtu** [comment]
code:
`langue_detector = LanguageDetectorBuilder.from_all_spoken_languages().build()`

samples, which was detected as `Sotho`.

- Can I use my credits?
- Hello
- i cannot make chcek in
- I pay tikets
- Hello whats going on
- hello how can i get more bagage
- thats it thank you
- Tell the promocode
- I want more kelo
- Rephrase
- can y cancel the tikets?

**Comment by iwtu** [comment]
well, there real user's inputs. It's not all about Naive Bayes language model. There is also reality element :)
Maybe some check/correct for typos?

**Comment by pemistahl** [comment]
This is a language identification library, not a spell-checking library. Go and use an additional spell checker if you need one.
