### ISSUE TITLE
Add fastspell to the comparison

### ISSUE THREAD

**Issue by marco-c** [pemistahl/lingua-py#188]
[fastspell](https://github.com/mbanon/fastspell) uses a combination of fastText and dictionaries to identify the language. It would be interesting to see how it compares to lingua-py.

**Comment by pemistahl** [comment]
Thank you for the suggestion. I will include it in the comparison.

**Comment by marco-c** [comment]
I have a local WIP patch, I could submit a PR in a few days.

**Comment by pemistahl** [comment]
Sounds good, PRs are always welcome. :)

**Comment by pemistahl** [comment]
@marco-c I've now updated the accuracy reports and plots to include FastSpell. It's more accurate than pure FastText, especially in aggressive mode. It also beats Lingua in low accuracy mode most of the time, even though the difference is not that big. Lingua in high accuracy mode is still unchallenged. Phew, lucky me. ;-)

In terms of runtime performance, FastSpell is significantly slower than FastText but on par with single-threaded Lingua in high accuracy mode.

Thanks again for your contribution. Let me know if you plan to use Lingua in one of your projects. I'm always curious.

<br>
<img src="https://raw.githubusercontent.com/pemistahl/lingua-py/main/images/plots/boxplot-average.png" alt="Average Detection Performance" />

**Comment by pemistahl** [comment]
Thank you for considering Lingua for Firefox. That would be amazing. :)

If the usage of dictionaries adds so much to accuracy, I will think about adding dictionaries to Lingua but without the performance penalty as in FastSpell. With Rust, that should be doable.
