### ISSUE TITLE
Performance comparison plots are not accessible

### ISSUE THREAD

**Issue by marco-c** [pemistahl/lingua-py#189]
The box plots and bar plots are very informative, but they are not accessible to everyone. It would be nice to also show the metrics in plain text in a table.

**Comment by pemistahl** [comment]
There is a [table](https://github.com/pemistahl/lingua-py#45-mean-median-and-standard-deviation) in the README but you have to expand it. It's collapsed by default so perhaps you missed it. Is this table what you are asking for or do you mean something different?

**Comment by marco-c** [comment]
Sorry, I had missed it! Might be valuable to mention it in the initial part of section 4, after the paragraph that says "Each of the following sections contains two plots [...]".
