### ISSUE TITLE
Add type annotations to v2.x

### ISSUE THREAD

**Issue by Vasniktel** [pemistahl/lingua-py#197]
Is there any plan to add type annotations to v2.x?

**Comment by Vasniktel** [comment]
Thanks, no pressure from my side. I thought they could be auto-generated but it seems that's not the case right now.

**Comment by pemistahl** [comment]
Fixed by commit https://github.com/pemistahl/lingua-rs/commit/ac9480ee82a99460fb55d8fe8e70606e01c23603, to be released shortly.
