### ISSUE TITLE
Cannot convert IsoCode or language string into the actual type

### ISSUE THREAD

**Issue by lhr0909** [pemistahl/lingua-py#225]
Since the Language class and IsoCode classes are Rust classes, it would be nice to provide the `from_str` methods back so I can dynamically import iso codes.

**Comment by pemistahl** [comment]
This feature has been implemented in https://github.com/pemistahl/lingua-rs/issues/410 now and will be part of the next Rust release 1.7.0 and the next Python release 2.1.0.
