### ISSUE TITLE
Getting Import error in Ubuntu and not able to install package using apt-get

### ISSUE THREAD

**Issue by asmita-mukherjee** [pemistahl/lingua-py#229]
### Discussed in https://github.com/pemistahl/lingua-py/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **thirtha-prasad** March  3, 2023</sup>
Getting below error, Package in installed using PIP and available in the python path.

ImportError: cannot import name 'Language' from 'lingua' (/usr/local/lib/python3.9/dist-packages/lingua/__init__.py)</div>

**Comment by pemistahl** [comment]
As @TomMoeras already found out, this error occurs when the Python package named `lingua` is installed which obviously uses the same namespace as my package. You don't need to uninstall the package, though. Just import it under a different namespace such as `import lingua as lng` or something like that.
