### ISSUE TITLE
Migrating form fasttext

### ISSUE THREAD

**Issue by lsmith77** [pemistahl/lingua-py#242]
Since after upgradin to spaCy 3.8, I needed to upgrade to Numpy 2.0, I am now unable to use FastText so I explored your library.

I ran into issues a few of the sentences in my test suite:

* `Are you Dominant` -> French has the highest confidence
* `😀 Power 𐐀 is our gooal my ninja` -> German has the highest confidence
* `El concepto que originó la creación de Pokémon, y por ende de rojo y azul, surgió a raíz del pasatiempo que Satoshi Tajiri.` French detected with a confidence of 0.36 and English with a confidence of 0.344

I realize these text are relatively short but I would still think these examples are sufficiently clearly English. Is there anything in terms of configuration I can do here?

here is the relevant code:

```
class LangDetection:
    def __init__(self):
        languages = [Language.ENGLISH, Language.FRENCH, Language.GERMAN]
        self.model = (
            LanguageDetectorBuilder.from_languages(*languages)
            .with_preloaded_language_models()
            .build()
        )

    def predict_lang(self, text):
        confidence_values = self.model.compute_language_confidence_values(text)

        result = []
        for confidence in confidence_values:
            if confidence.value < 0.3:
                break

            result.append(str(confidence.language.iso_code_639_1)[-2:].lower())

        return result
```

**Comment by pemistahl** [comment]
How is your third example supposed to be English? I don't see any English word in there. It looks like Spanish, actually. Your second example contains a spelling mistake which confuses the statistical algorithm.

Statistical approaches to language recognition are never 100 % correct. The sum of ngram probabilities for the returned language is simply greater than the sum of ngram probabilities for the language you expect. There is nothing that you can configure here except for the list of languages you want to take into the mix. If you include Spanish when building the detector, I'm sure it will return Spanish for your third example sentence.

**Comment by lsmith77** [comment]
Thank you for your feedback.

My application currently supports 3 languages, so my goal is to be able to detect if its one of those 3 or none of those three. But given your response, I should then deploy the model with support for as many languages as possible.

As for the issue with the typo, this was intentional since I do deal with text written by humans that may contain typos.

I guess FastText is simply really stellar with shorter text. Your algorithm does work really well for longer text. Also the ability to detect languages in subsections is really interesting.
