### ISSUE TITLE
There is no way to transform IsoCode639_1 string like "EN" into lingua.IsoCode639_1 object

### ISSUE THREAD

**Issue by NeFortex** [pemistahl/lingua-py#245]
lingua.Language and lingua.IsoCode639_1 and lingua.IsoCode639_3 aren't Enum so you can not make something like this

```
import lingua

for lang in lingua.Language:
    print('{:15} = {}'.format(lang.name, lang.value))
```

also there is no function to translate IsoCode639_1 string representation into IsoCode639_1 object

**Comment by pemistahl** [comment]
PyO3 enums do not (yet) behave exactly like native Python enums. You have to write your code a bit differently:

```python
>>> from lingua import Language
>>> for i, lang in enumerate(sorted(Language.all())):
...    print("{:15} = {}".format(lang.name, i))
...
AFRIKAANS       = 0
ALBANIAN        = 1
ARABIC          = 2
ARMENIAN        = 3
[...]
```

As for converting strings like "EN" into their actual type, there already exists issue #225 for that. So I'm closing this issue now since this is a duplicate.
