### ISSUE TITLE
Import of LanguageDetectorBuilder failed

### ISSUE THREAD

**Issue by geritwagner** [pemistahl/lingua-py#30]
When loading the LanguageDetectorBuilder as recommended in the readme, I received the following error:

from lingua import LanguageDetectorBuilder
...
ImportError: cannot import name 'LanguageDetectorBuilder' from 'lingua'

The following worked for me:

from lingua.builder import LanguageDetectorBuilder

**Comment by pemistahl** [comment]
Hi Gerit, thanks for reaching out to me.

I'm not able to reproduce your problem. The import `from lingua import LanguageDetectorBuilder` works fine for me. Which Python version are you using? In which exact context are you trying to import the library? Without more information, I cannot help you.

**Comment by geritwagner** [comment]
Hi Peter,

I am using Python 3.8.10 with lingua-language-detector==1.0.1. Not sure why it throws this error. The package setup seems to be ok...

**Comment by pemistahl** [comment]
I close this issue now. There is not enough information to help you. If you get a clue what might be wrong, feel free to re-open this issue and provide your findings. Thank you.

**Comment by Lv101Magikarp** [comment]
I ran into this issue because somehow I had the `lingua` package installed at the same time as the desired `lingua-language-detector` package and python was importing the wrong one.
