### ISSUE TITLE
Make the library compatible with Python versions < 3.9

### ISSUE THREAD

**Issue by Jourdelune** [pemistahl/lingua-py#5]
Hello, I try to use the module on google colab and I get this error during the installation:
```py
ERROR: Could not find a version that satisfies the requirement lingua-language-detector (from versions: none)
ERROR: No matching distribution found for lingua-language-detector
```
What are the requirements of this module?

**Comment by Jourdelune** [comment]
hi, no problem, I haven't been able to test it yet but it looks interesting!
I use that on google colabs:
```py
pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Python 3.7.12
```

I don't think it's due to pip because I was able to install other packets.

**Comment by pemistahl** [comment]
So, it seems the Python version is the problem. `pip` will most probably not install it because I've defined the minimum Python version to be 3.9. Can you upgrade your Python version from 3.7 to 3.9? This should solve the problem.

**Comment by Jourdelune** [comment]
On google colab, it is not possible :(

**Comment by pemistahl** [comment]
Can you please verify if you can install my library locally on your own computer?

I can try to make my library compatible with older Python versions starting from version 3.7. This should hopefully not be too difficult. I've developed the library using Python 3.9, that's why I've used this version as a minimum requirement.

**Comment by Jourdelune** [comment]
Ok, I'll wait for the evening to test (no computer with administrator rights at hand). But if it doesn't require too much work, why not support earlier versions of python, python3.9 is quite recent so not much used.

**Comment by pemistahl** [comment]
I've just released version 1.0.1 which is now compatible with Python >= 3.7.1. Can you please check again if you can install it now? Thanks.

**Comment by pemistahl** [comment]
Well, the goal of the entire library is to improve the accuracy on short texts. But there will always be cases which are misclassified because certain ngrams are more likely in one language than in the other. Statistical approaches are never 100% correct.

**Comment by Jourdelune** [comment]
Okep, I tested this but it always returns None, no matter what value you put, you have to put 0,01 to not return none, which loses its interest
```py
.with_minimum_relative_distance(0.25)
```
