### ISSUE TITLE
Wrong probabilities

### ISSUE THREAD

**Issue by 3a77** [pemistahl/lingua-py#62]
First of all, thank you for Lingua!

I've come across a few cases where Lingua now detects a different language than it did previously. I think the recent changes have introduced a bug: In some cases, `_look_up_ngram_probability` returns a probability even though the ngram is not present in the corresponding ngram table.

Test script:
```
from lingua import Language, LanguageDetectorBuilder
languages = [Language.ENGLISH, Language.GERMAN, Language.SPANISH]
detector = LanguageDetectorBuilder.from_languages(*languages).build()
print (detector._look_up_ngram_probability(Language.GERMAN, "teí"))
print (detector._look_up_ngram_probability(Language.ENGLISH, "teí"))
print (detector._look_up_ngram_probability(Language.SPANISH, "teí"))
```

Output before the August changes:
```
0.0
0.0
-8.193094053015134
```

Output after the August changes:
```
-14.266
-12.05
-8.195
```

**Comment by pemistahl** [comment]
Hi @3a77, thank you for this bug report. You are absolutely right. I misunderstood how [numpy.searchsorted](https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html) works. I'm going to release version 1.1.1 tomorrow which fixes it.
