### ISSUE TITLE
py.typed marker is missing

### ISSUE THREAD

**Issue by Vasniktel** [pemistahl/lingua-py#63]
Currently, mypy complains that the package is not marked with a [`py.typed` marker](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages). This effectively renders type annotations useless.

**Comment by pemistahl** [comment]
Thanks for the notice @Vasniktel. I will add the `py.typed` file to the next release.

**Comment by Vasniktel** [comment]
Thanks
