### ISSUE TITLE
Incorrect ISO 639-3 code for Urdu

### ISSUE THREAD

**Issue by pluiez** [pemistahl/lingua-py#64]
Hi, there is a typo in `lingua/language.py` at line 378:
```python
URDU = (70, IsoCode639_1.UR, IsoCode639_3.UKR, frozenset([_Alphabet.ARABIC]))
```

**Comment by pemistahl** [comment]
Thank you @pluiez. Of course, this is the wrong ISO 639-3 code for Urdu. I'm going to fix it.
