### ISSUE TITLE
Decrease memory and resource usage?

### ISSUE THREAD

**Issue by Jourdelune** [pemistahl/lingua-py#7]
Hi, your module works very well to detect the language, however it uses a lot of ram and power. Is there any way to reduce the memory usage and performance? I need to detect in all available languages, so I can't decrease the number of languages to load.

**Comment by pemistahl** [comment]
> Is there any way to reduce the memory usage and performance?

No. The only way, without decreasing detection accuracy, is to reduce the set of languages when building the `LanguageDetector`. Python, as a dynamically typed interpreted language, is slow. If you want to have more performance and less memory usage, please use the [Go](https://github.com/pemistahl/lingua-go) or [Rust](https://github.com/pemistahl/lingua-rs) implementation of *Lingua*. The [JVM](https://github.com/pemistahl/lingua) implementation is faster than the Python one but consumes even more memory, something around 4 GB.
